USE FACULADECOMMIT
GO

CREATE TABLE ALUNO(
Matricula INTEGER,
Nome      VARCHAR(40),
Telefone  VARCHAR(11),
DataEntrada  DATE)

INSERT INTO ALUNO VALUES ('12723490', 'MARIA', '2222-3344', GETDATE())

SELECT * FROM ALUNO

CREATE TABLE PROFESSOR (
Registro INTEGER,
Nome     VARCHAR(40),
TELEFONE VARCHAR(11),
SALARIO  INTEGER)

INSERT INTO PROFESSOR VALUES('44412', 'ANA', '555-6677', '1000')

SELECT * FROM PROFESSOR

CREATE TABLE ALUNO_TURMA (
CodTurma INTEGER,
Matricula INTEGER,
Media     INTEGER,
Faltas    INTEGER)

INSERT INTO ALUNO_TURMA VALUES ('1', '1', '8', '5')

SELECT * FROM ALUNO_TURMA

CREATE TABLE DISCIPLINA(
CodDisc  INTEGER,
Nome     VARCHAR(40),
CargaHor INTEGER)

INSERT INTO DISCIPLINA VALUES ('123','BANCO1', '60')

SELECT * FROM DISCIPLINA

CREATE TABLE TURMA(
CodTurma INTEGER,
Registro INTEGER,
Semestre INTEGER,
Ano      INTEGER,
CodDisc  INTEGER,)

INSERT INTO TURMA VALUES ('1','1', '2012','1','123')

SELECT * FROM TURMA
