USE BancoDeDados
GO

CREATE TABLE TESTE2 (
PROJETO          INTEGER,
TITULO           VARCHAR(100),
TIPO_DE_PROJETO  VARCHAR(100),
DATA_PROJETO     DATE)


INSERT INTO TESTE2 VALUES (1, 'PROJETO DE SISTEMA CNH', 'CNH', '2023-05-18')
INSERT INTO TESTE2 VALUES (2, 'PROJETO DE SISTEMA DE COLEGIO', 'COLEGIO', '2023-02-10')
INSERT INTO TESTE2 VALUES (3, 'PROJETO DA A3', 'A3', '2023-05-29')


SELECT * FROM TESTE2

SELECT *FROM TESTE2 ORDER BY DATA_PROJETO

SELECT * FROM TESTE2 WHERE PROJETO  IN (1,2)

SELECT * FROM TESTE2 WHERE TIPO_DE_PROJETO = 'CNH'

SELECT * FROM TESTE2 WHERE TIPO_DE_PROJETO LIKE '%CN%'

UPDATE TESTE2 SET TITULO = 'PROJETO DE SISTEMA CNH CONCLUIDO' WHERE PROJETO = 1

SELECT * FROM TESTE2

BEGIN TRAN
UPDATE TESTE2 SET TITULO = 'PROJETO DE SITEMA CNH CONCLUIDO - BACKUP' WHERE PROJETO = 1

--COMMIT
--ROLLBACK

SELECT * FROM TESTE2